export declare const API_URL = "https://api.zebedee.io";
export declare const API: {
    WALLET_ENDPOINT: string;
    CHARGES_ENDPOINT: string;
    STATIC_CHARGES_ENDPOINT: string;
    PAYMENTS_ENDPOINT: string;
    SEND_LN_ADDRESS_PAYMENT_ENDPOINT: string;
    VALIDATE_LN_ADDRESS_ENDPOINT: string;
    FETCH_CHARGE_FROM_LN_ADDRESS_ENDPOINT: string;
    SEND_GAMERTAG_PAYMENT_ENDPOINT: string;
    FETCH_GAMERTAG_PAYMENT_ENDPOINT: string;
    FETCH_USERID_FROM_GAMERTAG_ENDPOINT: string;
    FETCH_GAMERTAG_FROM_USERID_ENDPOINT: string;
    FETCH_CHARGE_FROM_GAMERTAG_ENDPOINT: string;
    WITHDRAWAL_REQUESTS_ENDPOINT: string;
    KEYSEND_PAYMENT_ENDPOINT: string;
    INTERNAL_TRANSFER_ENDPOINT: string;
    IS_SUPPORTED_REGION_ENDPOINT: string;
    FETCH_ZBD_PROD_IPS_ENDPOINT: string;
    BTCUSD_PRICE_TICKER_ENDPOINT: string;
};
//# sourceMappingURL=constants.d.ts.map